### ISSUE TITLE
How to disable?

### ISSUE THREAD

**Issue by ha-decodeit** [bitworking/react-scrollmagic#10]
I am trying to disable all scroll effects for mobile usage, based on the window width. 

Even though I set the _enabled_ property on the <Scene> to _false_ the animations are still running. 

Is this a bug or intended behavior?

Another thing I tried was accessing the Controller directly via refs and then call _this.controllerRef.state.controller.enabled(false)_ but this also did not have an effect. 

So what is the correct way on disabling scrollMagic?

**Comment by bitworking** [comment]
There is an enabled method on the Scene object. But it seems that I've not implemented that. If I find time on the weekend I'll release a new version..

**Comment by ha-decodeit** [comment]
That's great to hear! 
Do you think it would it be possible to expose all Scene and Controller functionality for some more advanced use cases?

**Comment by Mete36** [comment]
I am interested in this functionality as well. Has any progress been made for disabling the scroll effects?

**Comment by ILoyso** [comment]
by the way it's still relevant

**Comment by sorensenjg** [comment]
I also just ran into this situation. Any updates on disable functionality?

**Comment by bitworking** [comment]
I've added the enabled prop. Can be changed on-the-fly. Please test it out.
