### ISSUE TITLE
ScrollMagic dependency

### ISSUE THREAD

**Issue by antoinerousseau** [bitworking/react-scrollmagic#16]
Why is ScrollMagic copied in `lib/scrollmagic.js` instead of being imported as a npm dependency?
https://www.npmjs.com/package/scrollmagic
I can open a PR if you are interested.

**Comment by bitworking** [comment]
Because the npm package doesn't work for SSR.

**Comment by antoinerousseau** [comment]
I see!
I was about to suggest to upgrade it to the newest version but the diff looks heavy...
https://github.com/janpaepke/ScrollMagic/compare/v2.0.5...8e29c43556d59e96c1ff30aece0214073a5bc66f#diff-1b8d9ef6d550cf3e4ed7bcfa066d32f0
