### ISSUE TITLE
event handling

### ISSUE THREAD

**Issue by joperron** [bitworking/react-scrollmagic#2]
hello again! is there any way to fire functions using scrollmagic's .on? 

http://scrollmagic.io/docs/ScrollMagic.Scene.html#on

**Comment by bitworking** [comment]
The events start, end, enter and leave are triggered. Perhaps I will also add the other  events like change and destroy in the next version.

**Comment by bitworking** [comment]
The events start, end, enter and leave are triggered. Perhaps I'll add the other events like change and destroy in the next version.

**Comment by joperron** [comment]
Amazing thank you

**Comment by adithyamaheshb** [comment]
@bitworking 
Is there any chance that all the other events are gonna be added in the next version?
