### ISSUE TITLE
Best practice to split scenes into components

### ISSUE THREAD

**Issue by kegesch** [bitworking/react-scrollmagic#22]
When I want to use React I also usually want to separate as much code to different components. 
So if I want to split the different `Scene`s into different Components it does not work anymore because the `Controller` checks if the children have the type of `Scene`, but of course they have the type of the new component now. Based on this context, what is the best practice to separate scenes?

**Comment by kegesch** [comment]
I think it would be nice if the `Controller` always injects the `controller` into all its children independent of their type.

**Comment by kegesch** [comment]
Ok, so I figured that you can make a class component that derives from `Scene`. And then pass on the props with `<Scene {...this.props} />`. Then we have a nested `Scene` in another `Scene` which is quite a dirty workaround but well it works.

**Comment by kegesch** [comment]
And if you are eager to use functional components: Just call the functional component, which contains the `Scene`, as a function (so `React.createComponent()` does not get called).

**Comment by kegesch** [comment]
After some time trying out I think it's quite limiting that the `Scene`s must be direct children of Controller. (Same goes for nested `Lifetimes` in `react-gsap`.) @bitworking What do you think of refactoring and use [React's context api](https://reactjs.org/docs/context.html)?

**Comment by bitworking** [comment]
Yes that is something I want to refactor if I have time. Hmm..Context API is a good idea, but every Controller or in react-gsap every Tween/Timeline needs to be a Provider because you can nest these components. And I don't think that is possible with context, because I would need the nearest parent provider. But I have to look into it..

**Comment by kegesch** [comment]
I am currently trying to implement it. 
React automatically finds the neared parent provider. From the website: 

```javascript
  // Assign a contextType to read the current theme context.
  // React will find the closest theme Provider above and use its value.
  // In this example, the current theme is "dark".
  static contextType = ThemeContext;
```

**Comment by bitworking** [comment]
Nice, didn't know that. Cool, I'm excited if you can make it work!

**Comment by kegesch** [comment]
I started implementing it in `react-gsap`. In[ this commit](https://github.com/kegesch/react-gsap/commit/73afcee157c250722eefaf71af0abca177a32229) you can see what i've done. I think it would work the same way with the controller. 
I just had one problem, that nested timelines didn't propagate their progress to a child timeline. Maybe I missed something.
