### ISSUE TITLE
Struggling while trying to achieve a certain scenario

### ISSUE THREAD

**Issue by ChrizzDF** [bitworking/react-scrollmagic#23]
Hi guys,
thanks for this awesome package!

I already made some nice animations, but now, working on a new project, I don't know how to approach it and I don't even know if ScrollMagic is capable of doing what I want.

This is what I want to achieve: : https://dashretail.eu/

When I scroll down, it should
- trigger and play a defined animation
- disable any further scrolling while an animation is playing
- animated the reverse way when I scroll up

Hoping for any kind of support.

Thanks in advance!

**Comment by bitworking** [comment]
Scrollmagic is not really built for these whole page transition effects. You should better use something like this:  https://alvarotrigo.com/fullPage/
