### ISSUE TITLE
How can I disable this Scene on mobile?

### ISSUE THREAD

**Issue by thijs666** [bitworking/react-scrollmagic#26]
I'm kinda new to scrollmagic and react in general. I'm stuck on this problem. Any ideas how I can solve this? 

I know that I can use a prop for disabling it, but how can I change that boolean on the fly based on the screen width?

The site is being made in Gatsby JS.

Help is greatly appreciated!

          <Controller>
          <Scene
            duration={500}
            pin={true}
            enabled={true}
            >
             {(progress) => (
          <Tween 
          from={{
            css: {
              transform: 'translate3d(0px, 0px, 0px) scale(0, 1)'
            },
            ease: 'Strong.easeOut',
          }}
          to={{
            css: {
              transform: 'translate3d(0px, 0px, 0px) scale(1, 1)'
          },
          ease: 'Strong.easeOut'
        }}     
          totalProgress={progress}
            paused
        >
            <div className="background-progress"></div>
            </Tween>
            )}
          </Scene>
          </Controller>

**Comment by tomasz89nowak** [comment]
I think you could use [react-media](https://github.com/ReactTraining/react-media) to do this.
```
<Media queries={{
  small: "(max-width: 599px)",
  medium: "(min-width: 600px) and (max-width: 1199px)",
  large: "(min-width: 1200px)"
}}>
   {matches => (
     <Scene
        enabled={matches.large}
     >...</Scene>
   )}
</Media>
```
