### ISSUE TITLE
Pinned scene not working in Safari

### ISSUE THREAD

**Issue by johntbb** [bitworking/react-scrollmagic#36]
I have a pinned scene on this page:

https://deuren.netlify.app/internal-doors/pre-hung-internal-door-sets

It doesn't work as expected on Safari. If you scroll to the scene quickly, then it will actually scroll past the intended pin point and stick there. And when you scroll up, the browser completely ignores the fixed positioning.

**Comment by bitworking** [comment]
react-scrollmagic is just a wrapper for ScrollMagic. This bug seems to be related to this library. Have you looked at their issues? Else you could try ScrollTrigger from gsap which I also have a react wrapper for: https://bitworking.github.io/react-gsap/src-components-scroll-trigger

**Comment by johntbb** [comment]
Thanks! I'll have a look at the GSAP solution first.

It's more that I've been scratching my head over the issue for a few days and seems to now be beyond the scope of my skillset, so wondered if there was a known issue or if I'd uncovered something.

Thanks again.

**Comment by johntbb** [comment]
@bitworking just wanted to let you know I managed to rework this to use the react-gsap package instead and it now works well across all browsers.

Thanks for your help!
