### ISSUE TITLE
React alternatives to this library

### ISSUE THREAD

**Issue by andretti1977** [bitworking/react-scrollmagic#48]
Since the project seems to be abandoned, do exists currently supported react alternatives? I'd like to have the "pin" option but need callbacks to the entering or leaving items

**Comment by bitworking** [comment]
Yes, better use GSAP ScrollTrigger. I have a helper component for that in my other react-gsap library: https://bitworking.github.io/react-gsap/src-components-scroll-trigger

**Comment by bitworking** [comment]
I also put a note to the readme

**Comment by zeckdude** [comment]
This doesn't seem to all of the same things shown in the examples in this repo. If it does, it would be nice to include examples (with source code) please.
