### ISSUE TITLE
How to declaratively add a event handler on a given Scene

### ISSUE THREAD

**Issue by jacargentina** [bitworking/react-scrollmagic#8]
It is possible somehow to add an eventhandler in a `<Scene/>`?

I would like to handle, for example, the `start` event. If its not possible, i can make a PR for adding support.

**Comment by bitworking** [comment]
If you use a function as child the event is the second parameter. Example: https://github.com/bitworking/react-scrollmagic/blob/master/example/src/components/ScrollMagicExamples/ClassToggle.js
